# Generated by Django 3.2 on 2021-05-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Supplier', '0002_auto_20210512_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supplier_reg_tbl',
            new_name='supplier_reg_table',
        ),
    ]
