# Generated by Django 3.2 on 2021-05-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Supplier', '0004_auto_20210512_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supp_reg_table',
            old_name='supName',
            new_name='supplierName',
        ),
    ]
