# Generated by Django 3.2 on 2021-05-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Supplier', '0005_rename_supname_supp_reg_table_suppliername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supp_reg_table',
            name='pdtName',
        ),
    ]
