# Generated by Django 3.2 on 2021-05-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Supplier', '0006_remove_supp_reg_table_pdtname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supp_reg_table',
            old_name='supplierName',
            new_name='supName',
        ),
    ]
