# Generated by Django 3.2 on 2021-05-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Supplier', '0009_supp_reg_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='supp_reg_table',
            new_name='s_reg_table',
        ),
    ]
