# Generated by Django 3.2 on 2021-05-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pdt_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtname', models.CharField(max_length=100)),
                ('pdtimage', models.FileField(upload_to='media')),
                ('pdtprice', models.CharField(max_length=100)),
                ('pdttax', models.CharField(max_length=100)),
                ('pdtquality', models.CharField(max_length=100)),
                ('pdtstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='supp_reg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supName', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
