# Generated by Django 3.2 on 2021-05-13 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0002_pdt_category_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdt_category_add',
            old_name='cat_name',
            new_name='pdtcatname',
        ),
        migrations.RenameField(
            model_name='pdt_category_add',
            old_name='status',
            new_name='pdtcatstatus',
        ),
    ]
