# Generated by Django 3.2 on 2021-05-13 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0004_stock_management'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_management',
            old_name='prodid',
            new_name='pdtid',
        ),
    ]
