# Generated by Django 3.2 on 2021-05-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0005_rename_prodid_stock_management_pdtid'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
                ('mdate', models.DateTimeField(max_length=100)),
                ('mperformance', models.CharField(max_length=100)),
            ],
        ),
    ]
