# Generated by Django 3.2 on 2021-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0006_machine_manage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='machine_manage',
        ),
    ]
