# Generated by Django 3.2 on 2021-05-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0007_delete_machine_manage'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine_add',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinename', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('machineperformance', models.CharField(max_length=100)),
            ],
        ),
    ]
