# Generated by Django 3.2 on 2021-05-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0008_machine_add'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock_management',
            new_name='stock_mg',
        ),
        migrations.DeleteModel(
            name='supp_reg_table',
        ),
    ]
