# Generated by Django 3.2 on 2021-05-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0009_auto_20210517_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_mg',
            old_name='pdtid',
            new_name='proid',
        ),
    ]
