# Generated by Django 3.2 on 2021-05-23 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0010_rename_pdtid_stock_mg_proid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock_mg',
            new_name='stock_manage',
        ),
    ]
