# Generated by Django 3.2 on 2021-05-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0011_rename_stock_mg_stock_manage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stock_manage',
        ),
    ]
