# Generated by Django 3.2 on 2021-05-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0013_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='stocks12',
        ),
    ]
