# Generated by Django 3.2 on 2021-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0007_auto_20210530_2104'),
        ('GUE_Admin123', '0014_rename_stocks_stocks12'),
    ]

    operations = [
        migrations.DeleteModel(
            name='machine_add',
        ),
        migrations.DeleteModel(
            name='pdt_category_add',
        ),
        migrations.RemoveField(
            model_name='stocks12',
            name='productid',
        ),
        migrations.DeleteModel(
            name='pdt_reg_tbl',
        ),
        migrations.DeleteModel(
            name='stocks12',
        ),
    ]
