# Generated by Django 3.2 on 2021-05-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GUE_Admin123', '0015_auto_20210530_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdt_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtname', models.CharField(max_length=100)),
                ('pdtimage', models.CharField(max_length=100)),
                ('pdtprice', models.CharField(max_length=100)),
                ('pdttax', models.CharField(max_length=100)),
                ('pdtquality', models.CharField(max_length=100)),
                ('pdtstatus', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
