# Generated by Django 3.2 on 2021-05-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0016_pdt_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='sup_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
