# Generated by Django 3.2 on 2021-05-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0017_sup_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.CharField(max_length=100)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GUE_Admin123.pdt_reg_tbl')),
            ],
        ),
    ]
