# Generated by Django 3.2 on 2021-05-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0018_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtcatname', models.CharField(max_length=100)),
                ('pdtcatstatus', models.CharField(max_length=100)),
            ],
        ),
    ]
