# Generated by Django 3.2 on 2021-05-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Admin123', '0020_machine_req_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='stocks',
            new_name='stock',
        ),
    ]
