# Generated by Django 3.2 on 2021-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_reg_tbl',
            name='empsalary',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
