# Generated by Django 3.2 on 2021-05-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0003_alter_emp_reg_tbl_empsalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_reg_tbl',
            name='empsalary',
        ),
    ]
