# Generated by Django 3.2 on 2021-05-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0004_remove_emp_reg_tbl_empsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_reg_tbl',
            name='empsalary',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
