# Generated by Django 3.2 on 2021-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0006_machine_repair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_repair',
            name='employee_is',
        ),
        migrations.RemoveField(
            model_name='machine_repair',
            name='machine_id',
        ),
        migrations.DeleteModel(
            name='emp_reg_tbl',
        ),
        migrations.DeleteModel(
            name='machine_repair',
        ),
    ]
