# Generated by Django 3.2 on 2021-05-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GUE_Employee', '0007_auto_20210530_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('dtime', models.DateField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('passwd', models.CharField(max_length=100)),
            ],
        ),
    ]
