# Generated by Django 3.2 on 2021-06-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0008_emp_reg_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdt_req_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdtname', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supname', models.CharField(max_length=100)),
            ],
        ),
    ]
