# Generated by Django 3.2 on 2021-06-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Employee', '0009_pdt_req_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_reg_tbl',
            name='vrf',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
