# Generated by Django 3.2 on 2021-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Customer', '0002_cust_reg_tbl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_reg_tbl',
            old_name='password',
            new_name='password1',
        ),
    ]
