# Generated by Django 3.2 on 2021-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GUE_Customer', '0003_rename_password_cust_reg_tbl_password1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cust_feedback_tbl',
        ),
        migrations.DeleteModel(
            name='cust_reg_tbl',
        ),
    ]
