# Generated by Django 3.2 on 2021-05-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GUE_Customer', '0004_auto_20210530_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
